Modules/User/Http/routes.php
<?php

$adminPrefix = env('ADMIN_PREFIX', 'admin');
$authPrefix = env('AUTH_PREFIX', 'auth');

Route::group(['middleware' => ['web', 'auth.admin', 'noajax'], 'prefix' => $adminPrefix, 'namespace' => 'Modules\User\Http\Controllers'], function() {
    Route::resource('user', 'UserController', ['as' => 'admin']);
    Route::resource('role', 'RoleController', ['as' => 'admin']);
    Route::get('subscription', ['as' => 'admin.settings.subscription', 'uses' => 'UserController@showSubscriptionOpt'])->middleware('permission:settings.edit_general');
    Route::post('subscription', ['as' => 'admin.settings.subscription.post', 'uses' => 'UserController@saveSubscriptionOpt'])->middleware('permission:settings.edit_general');
    Route::get('profile', ['as' => 'admin.settings.profile', 'uses' => 'UserController@profile'])->middleware('permission:user.profile');
    Route::post('profile', ['as' => 'admin.settings.profile.save', 'uses' => 'UserController@saveProfile'])->middleware('permission:user.profile');
});

Route::group(['middleware' => ['web', 'init', 'noajax'], 'prefix' => $authPrefix, 'namespace' => 'Modules\User\Http\Controllers'], function () {
    # Login
    Route::get('login', ['middleware' => 'auth.guest', 'as' => 'login', 'uses' => 'AuthController@getLogin']);
    Route::post('login', ['as' => 'login.post', 'uses' => 'AuthController@postLogin']);
    # Register
    if (env('ALLOW_SUBSCRIBE', false)) {
        Route::get('register', ['middleware' => 'auth.guest', 'as' => 'register', 'uses' => 'AuthController@getRegister']);
        Route::post('register', ['as' => 'register.post', 'uses' => 'AuthController@postRegister']);
    }
    # Account Activation
    Route::get('activate/{userId}/{activationCode}', 'AuthController@getActivate');
    # Reset password
    Route::get('reset', ['as' => 'reset', 'uses' => 'AuthController@getReset']);
    Route::post('reset', ['as' => 'reset.post', 'uses' => 'AuthController@postReset']);
    Route::get('reset/{id}/{code}', ['as' => 'reset.complete', 'uses' => 'AuthController@getResetComplete']);
    Route::post('reset/{id}/{code}', ['as' => 'reset.complete.post', 'uses' => 'AuthController@postResetComplete']);
    # Logout
    Route::get('logout', ['as' => 'logout', 'uses' => 'AuthController@getLogout']);
});

Modules/User/Http/Controllers/RoleController.php
<?php

namespace Modules\User\Http\Controllers;

use Illuminate\Routing\Controller;
use Modules\User\DataTables\RoleDataTable;
use Modules\User\Contracts\RoleRepository;
use Modules\User\Permissions\PermissionManager;
use Modules\User\Http\Requests\RolesRequest;

class RoleController extends Controller
{
    /**
     * @var RoleRepository
     */
    private $role;
    private $permissions;

    public function __construct(PermissionManager $permissions, RoleRepository $role)
    {
        $this->permissions = $permissions;
        $this->role = $role;
        $this->middleware('permission:user.roles.index', ['only' => ['index']]);
        $this->middleware('permission:user.roles.create', ['only' => ['create', 'store']]);
        $this->middleware('permission:user.roles.edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:user.roles.destroy', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(RoleDataTable $dataTable)
    {
        return $dataTable->render('user::admin.roles.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('user::admin.roles.create',
                ['permissions' => $this->permissions->all()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  RolesRequest $request
     * @return Response
     */
    public function store(RolesRequest $request)
    {
        $data = $this->mergeRequestWithPermissions($request);

        $this->role->create($data);

        return redirect()->route('admin.role.index')
            ->withSuccess(trans('messages.admin.users.role.create-success'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int      $id
     * @return Response
     */
    public function edit($id)
    {
        if (!$role = $this->role->find($id)) {
            return redirect()->route('admin.role.index')
                ->withError(trans('role not found'));
        }

        return view('user::admin.roles.edit', 
            ['permissions' => $this->permissions->all(), 'role'=>$role]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int          $id
     * @param  RolesRequest $request
     * @return Response
     */
    public function update($id, RolesRequest $request)
    {
        $data = $this->mergeRequestWithPermissions($request);

        $this->role->update($id, $data);

        return redirect()->route('admin.role.index')
            ->withSuccess(trans('messages.admin.users.role.update-success'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int      $id
     * @return Response
     */
    public function destroy($id)
    {
        $this->role->delete($id);

        return redirect()->route('admin.role.index')
            ->withSuccess(trans('messages.admin.users.role.delete-success'));
    }
    
    private function mergeRequestWithPermissions(RolesRequest $request)
    {
        $permissions = $this->permissions->clean($request->permissions);

        return array_merge($request->all(), ['permissions' => $permissions]);
    }
}

Modules/User/Resources/views/admin/roles/create.blade.php
@extends('base::layouts.default')

@section('breadcrumbs')
{!!Breadcrumbs::render()!!}
@endsection

@section('content')
<div class="row">
    <div class="col-md-12" >
        <div class="box box-primary">
            <div class="box-header with-border">
                <i class="fa fa-plus-square-o"></i> {{ Lang::get('messages.admin.users.roles.create') }}
                <div class="box-tools">
                    {{ link_to_route('admin.role.index', Lang::get('messages.admin.manga.back'), [], array('class' => 'btn btn-default btn-xs', 'role' => 'button')) }}
                </div>
            </div>
            {{ Form::open(array('route' => 'admin.role.store')) }}
            <div class="box-body">
                <div class="form-group">
                    {{Form::label('name', Lang::get('messages.admin.users.roles.role-name'))}}
                    {{Form::text('name', '', array('class' => 'form-control'))}}
                    {!! $errors->first('name', '<label class="error" for="name">:message</label>') !!}
                </div>

                <fieldset>
                    <legend>Permissions</legend>
                    @include('user::admin.partials.permissions-create')
                </fieldset>
            </div>
            <div class="box-footer">
                {{ Form::submit(Lang::get('messages.admin.settings.save'), array('class' => 'btn btn-primary pull-right')) }}
            </div>
            {{ Form::close() }}
        </div>
    </div>
</div>
@endsection

Modules/User/Resources/views/admin/roles/edit.blade.php
@extends('base::layouts.default')

@section('breadcrumbs')
{!!Breadcrumbs::render()!!}
@endsection

@section('content')
<div class="row">
    <div class="col-md-12" >
        <div class="box box-primary">
            <div class="box-header with-border">
                <i class="fa fa-pencil-square-o"></i> {{ Lang::get('messages.admin.users.roles.edit') }}
                <div class="box-tools">
                    {{ link_to_route('admin.role.index', Lang::get('messages.admin.manga.back'), [], array('class' => 'btn btn-default btn-xs', 'role' => 'button')) }}
                </div>
            </div>
            {{ Form::open(array('route' => array('admin.role.update', $role->id), 'method' => 'PUT')) }}
            <div class="box-body">
                <div class="form-group">
                    {{Form::label('name', Lang::get('messages.admin.users.roles.role-name'))}}
                    {{Form::text('name', $role->name, array('class' => 'form-control'))}}
                    {!! $errors->first('name', '<label class="error" for="name">:message</label>') !!}
                </div>

                <fieldset>
                    <legend>{{ Lang::get('messages.admin.users.roles.select-perms') }}</legend>
                    @include('user::admin.partials.permissions', ['model' => $role])
                </fieldset>
            </div>
            <div class="box-footer">
                {{ Form::submit(Lang::get('messages.admin.settings.update'), array('class' => 'btn btn-primary pull-right')) }}
            </div>
            {{ Form::close() }}
        </div>
    </div>
</div>
@endsection

Modules/User/Resources/views/admin/roles/index.blade.php
@extends('base::layouts.default')

@section('head')
<link rel="stylesheet" href="{{asset('vendor/datatables/jquery.dataTables.min.css')}}">
<link rel="stylesheet" href="{{asset('vendor/datatables/buttons.dataTables.min.css')}}">

<script src="{{asset('vendor/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('vendor/datatables/dataTables.buttons.min.js')}}"></script>
<script src="{{asset('vendor/datatables/buttons.server-side.js')}}"></script>
@endsection

@section('breadcrumbs')
{!!Breadcrumbs::render()!!}
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">
                    <i class="fa fa-bars"></i> {{ Lang::get('messages.admin.users.roles') }}
                </h3>
                <div class="box-tools">
                    <a class="btn btn-primary btn-sm"
                       href="{{route('admin.role.create')}}">
                        <i class="fa fa-plus"></i> {{ Lang::get('messages.admin.users.roles.add') }}
                    </a>
                </div>
            </div>
            <div class="box-body">
                {!! $dataTable->table() !!}
            </div>
        </div>
    </div>
</div>

{!! $dataTable->scripts() !!}
@endsection